<?php
require "../config/config.php";
require "../config/helper.php";
require "../includes/header.php";
require_once "../vendor/autoload.php";

// Initialize the StripeClient with the secret key
$stripe = new \Stripe\StripeClient($secret_key);

// Create a charge using the StripeClient object
$charge = $stripe->charges->create([
    'source' => $_POST['stripeToken'], // The token generated by Stripe.js
    'amount' => $_SESSION['summary_total_price'] * 100, // Total amount in cents
    'currency' => 'usd',
]);

// Output success message
echo "paid";
?>